CosmetologyCenter/CosmetologyCenter/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),

    path('', include('main.urls')),
    path('cart/', include('cart.urls')),
    path('doctors/', include('doctors.urls')),
    path('services/', include('services.urls')),
    path('appointments/', include('appointments.urls')),
    path('stats/', include('stats.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

CosmetologyCenter/cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_details, name='cart_details'),
    path('add_to_cart/<int:service_id>/', views.add_to_cart, name='add_to_cart'),
    path('remove_in_cart/<int:appointment_item_id>/', views.cart_remove, name='cart_remove'),
]

CosmetologyCenter/main/urls.py
from django.urls import path
from . import views


app_name = 'main'

urlpatterns = [ 
    path('', views.home, name='home'),
    path('about/', views.about, name='about'),
    path('prices/', views.price_list, name='price-list'),
    path('news/', views.news, name = 'news'),
    path('FAQ/', views.faq, name = 'FAQ'),
    path('sandbox/', views.sandbox, name = 'sandbox'),
    path('create_rewiew/', views.create_review, name = 'create_rewiew'),
    path('rewiews/', views.reviews, name = 'rewiews'),
    path('privacy_policy/', views.privacy_policy, name = 'privacy_policy'),
    path("promotional_code/", views.promotional_code, name='promotional_code'),
    path('vacancies/', views.vacancies, name = 'vacancies'),
    path('js_sandbox/', views.js_sandbox, name = 'js_sandbox')
]

CosmetologyCenter/services/urls.py
from django.urls import path
from . import views

app_name = 'services'

urlpatterns = [ 
    path('', views.index, name='services-list'),
    path('service/<int:pk>/', views.ServiceDetailView.as_view(), name='service-detail'),
]

CosmetologyCenter/main/models.py
from django.db import models
from django.core.validators import RegexValidator
from django.core.validators import MinValueValidator, MaxValueValidator
from django.urls import reverse


# Create your models here.
class Client(models.Model):
    first_name = models.CharField(max_length=20, help_text='Enter first name')
    last_name = models.CharField(max_length=20, help_text='Enter last name')
    date_of_birth = models.DateField(help_text="Enter date of birth")
    email = models.EmailField(help_text="Enter email")
    town = models.CharField(help_text="Enter town", max_length=30, default='Minsk')
    phone_number = models.CharField(max_length=25, help_text='Enter phone number', validators=[RegexValidator(
        regex=r'^(\+375 \(29\) [0-9]{3}-[0-9]{2}-[0-9]{2})$',
        message='Format +375 (29) XXX-XX-XX')])

    def __str__(self):
        return f"{self.last_name} {self.first_name}"


class News(models.Model):
    title = models.CharField(max_length=200, help_text="Enter title")
    essence = models.CharField(max_length=200, help_text="Enter essence")
    photo = models.ImageField(upload_to='images', blank=True)
    description = models.TextField(help_text="Enter description")

    def __str__(self):
        return self.description

    def get_absolute_url(self):
        return reverse('main:news', args=[str(self.id)])


class FAQ(models.Model):
    question = models.CharField(max_length=150, help_text="Enter question")
    answer = models.TextField(help_text="Enter answer")
    date_added = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.question

    def get_absolute_url(self):
        return reverse('main:FAQ', args=[str(self.question)])


class Review(models.Model):
    text = models.TextField(help_text="Enter review")
    rating = models.IntegerField(help_text="Enter rating from 0 to 10",  validators=[
        MinValueValidator(0, message="The number cannot be less than 0"),
        MaxValueValidator(10, message="The number cannot be more than 10")
    ])
    date_added = models.DateTimeField(auto_now_add=True)
    author = models.CharField(max_length=20, default='')
    def get_absolute_url(self):
        return reverse('main:reviews', args=[str(self.text)])

    def __str__(self):
        return f'{self.text}'


class Banner(models.Model):
    image = models.ImageField(upload_to='images')
    target_url = models.URLField()

    def __str__(self):
        return f"Banner for {self.target_url}"


class Job(models.Model):
    type_of_job = models.CharField(max_length=70, help_text='Enter type of ypor job')
    description = models.TextField(help_text="Enter description", default="")
    is_actual = models.BooleanField(help_text="Is actual?", default=True)

    def __str__(self):
        return self.type_of_job


class Promotional_code(models.Model):
    value = models.TextField(help_text="Enter promocode")
    is_actual = models.BooleanField(default=True)
    discount = models.IntegerField(help_text="Enter discount from 1 to 25", default=10, validators=[
        MinValueValidator(1, message="The number cannot be less than 1"),
        MaxValueValidator(25, message="The number cannot be more than 25")])

    def __str__(self):
        return self.value

CosmetologyCenter/main/views.py
from django.shortcuts import render, redirect
from services.models import Service, ServiceType
from .models import News, FAQ, Review, Banner, Promotional_code, Job
from .form import ReviewForm
import requests
import logging


logger = logging.getLogger(__name__)

# Create your views here.
def home(request):
    logger.info('Method home')

    services = Service.objects.all()[:2]
    news = News.objects.first()
    banners = Banner.objects.all()

    return render(request, 'main/home.html', context={'services': services, 'news': news, 'banners': banners})

def about(request):
    return render(request, 'main/about.html')

def price_list(request):
    logger.info('Method price_list')

    service_types = ServiceType.objects.all()
    services_by_type = {}
    
    for service_type in service_types:
        services = Service.objects.filter(service_type=service_type)
        services_by_type[service_type] = services

    return render(request, 'main/price-list.html', {'services_by_type': services_by_type, 'service_types': service_types})


def news(request):
    logger.info('Method news')
    
    news = News.objects.all()
    return render(request, 'main/news.html', {'news': news})


def faq(request):
    logger.info('Method faq')

    faq = FAQ.objects.all()
    return render(request, 'main/FAQ.html', {'faq': faq})


def privacy_policy(request):
    logger.info('Method privacy_policy')

    return render(request, 'main/privacy_policy.html')


def js_sandbox(request):
    return render(request, 'main/js_sandbox.html')


def reviews(request):
    logger.info('Method reviews')

    reviews = Review.objects.all()
    return render(request, 'main/reviews.html', {'reviews': reviews})


def create_review(request):
    logger.info('Method create_review')

    if request.method == "POST":
        form = ReviewForm(request.POST)
        if form.is_valid():
            review = Review.objects.create(text=request.POST.get('text'),
                                           rating=request.POST.get('rating'),
                                           author=request.POST.get('author'),
                                           ),

            return redirect('main:rewiews')

    else:
        form = ReviewForm()
        return render(request, "main/create_review.html", {"form": form})
    return redirect('main:home')


def sandbox(request):
    logger.info('Method sandbox')

    joke = requests.get('https://official-joke-api.appspot.com/jokes/random').json()
    dog = requests.get('https://dog.ceo/api/breeds/image/random').json()

    return render(request, 'main/sandbox.html',context={'joke': joke['setup'] + joke['punchline'], 
                                                  'dog': dog['message']})


def promotional_code(request):
    actual_promotional_code = Promotional_code.objects.filter(is_actual=True)
    archive_promotional_code = Promotional_code.objects.filter(is_actual=False)
    return render(request, 'main/promotional_code.html', {'actual_promotional_code': actual_promotional_code, 'archive_promotional_code': archive_promotional_code})


def vacancies(request):
    vacancies = Job.objects.filter(is_actual=True)
    return render(request, 'main/job.html', {'vacancies': vacancies})


def my_view(request):
    logger.debug('Это сообщение с уровнем DEBUG')
    logger.info('Это сообщение с уровнем INFO')
    logger.warning('Это сообщение с уровнем WARNING')
    logger.error('Это сообщение с уровнем ERROR')
    logger.critical('Это сообщение с уровнем CRITICAL')

CosmetologyCenter/main/templates/main/FAQ.html
{% extends "layout.html" %}

{% load static %}

{% block head %}
<link rel="stylesheet" href="{% static 'css/main/FAQ.css'%}"/>

<title>FAQ</title>
{% endblock %}

{% block main %}
<div class="faq-content">
    <h1>Часто Задаваемые Вопросы</h1>

    <ul>
        {%for F in faq%}
        <li>
            <details>
                <summary>
                    <p> <strong>{{F.question}}</strong></p>
                </summary>
                <p>{{F.answer}}</p>
                <p>Добавлено: {{F.date_added}}</p>
            </details>

        </li>

        {%endfor%}

    </ul>
</div>
{% endblock %}

CosmetologyCenter/main/templates/main/about.html
{% extends "layout.html" %}

{% load static %}

{% block head %}
<link rel="stylesheet" href="{% static 'css/main/about.css'%}"/>

<title>О нас</title>
{% endblock %} 

{% block main %}

<section id="about">
    <h1>О нашей компании</h1>
    <p>Клинический центр пластической хирургии и медицинской косметологии г. Минска» . 
        Успех нашей работы основывается на более чем 40-летнем опыте, 
        высококвалифицированной команде специалистов и использовании современных технологий и оборудования.
        <dfn title=" Добро пожаловать в CosmetologyCenter.by "> – вашему надежному партнеру
            в
            мире
            косметологии! Мы гордимся тем, что предлагаем широкий ассортимент
            высококачественных услуг, а также профессиональное обслуживание и
            индивидуальный подход к каждому клиенту. Наш <a href="#History">опыт и преданность качеству</a>
            сделали нас лидерами в отрасли, и мы всегда готовы помочь вам.</dfn>
    </p>
    <h2>Основными целями и задачами центра являются:</h2>
    <ul>
        <li>
            Оказание <strong>высококвалифицированных</strong> специализированных
            платных  медицинских услуг по косметологии, пластической эстетической хирургии,
            физиотерапии, стоматологии терапевтической;
        </li>
        <li>
            Внедрение <strong>новых</strong> медицинских технологий, методик, операций;
        </li>
        <li>
            Постоянное <strong>усовершенствование</strong> навыков врачей и средних медицинских работников;</strong> 
        </li>
    </ul>
    
    <p>
        В клиническом центре функционируют следующие лечебные структурные подразделения:
         отделение пластической эстетической хирургии, группа анестезиологии и реанимации, 
         три косметологических отделения, физиотерапевтический кабинет, стоматологический кабинет.
    </p>
    
    <p>
        <a href="#contacts">Свяжитесь с нами сегодня</a>, чтобы задать все интересующие вас вопросы!
    </p>
    
    <h1>Наше видео</h1>
    
    <div style="text-align: center;">
        <iframe width="560" height="315" src="https://www.youtube.com/embed/W5dsZ5RRu-w?si=ucYj85W-fi_3hsHc" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>
    </div>
    
    <h1>Наш логотип:</h1>
    <div style="text-align: center;">
    
        <img class="logo-img" src="../media/images/lotus.png" alt="Логотип"  width="300em" height="200em" />
    </div>
</section>


<section id="history">
    <h1>История нашей компании</h1>

    <h2>1980: Основание</h2>
    <p>1 декабря 1980г. решением Мингорисполкома в г.Минске была открыта косметологическая лечебница.</p>
    
    <h2>1996: Реорганизация</h2>
    <p>В сообтветствии с решением Мингорисполкома от 27 июня 1996 г. и приказом Министерства здравоохранения в связи
         с созданием современной лечебно-диагностической базы космметоогическая лечебница была реорганизована в клинический
          центр пластической хирургии и медицинской косметологии г.Минска</p>
    
    <h2>Открытие КО №3 на Жиновича</h2>
    <p>Открытие</p>
</section>

<section id="contacts">
    <h1>Реквизиты</h1>

    <p><strong>Адрес:</strong> ул. Петруся бровки 6, Минск, 220004.</p>
    <p><strong>Телефон:</strong>+375 (29) 123-45-67</p>
    <p><strong>Электронная почта:</strong> <a href="#">CosmetologyCenter@gmail.com</a></p>
    
    <h2>Часы работы:</h2>
    <p>Понедельник - Пятница: 9:00 AM - 6:00 PM</p>
    <p>Суббота: Выходной</p>
    <p>Воскресенье: Выходной</p>
    
    <h2>Социальные медиа:</h2>
    <ul>
        <li><a href="#">Facebook</a></li>
        <li><a href="#">Instagram</a></li>  
    </ul>
    
    <h2>Номера для обратной связи:</h2>
    <ul>
        <li>Поддержка: +375 (29) 123-45-67</li>
        <li>Техническая помощь: +375 (29) 123-45-67</li>
    </ul>
</section>

<figure id="certificate" class="certificate">
    <h1>СЕРТИФИКАТ</h1>
    <p>Настоящим удостоверяется, что</p>
    <h2>CosmetologyCenter</h2>
    <p>является официальным владельцем и администратором веб-сайта</p>
    <h3>CosmetologyCenter.by</h3>
    <p>в течение срока действия данного сертификата.</p>
    <p>Сертификат выдан 01.01.2015 и действителен до 01.01.2025.</p>
    <p>Этот сертификат подтверждает, что CosmetologyCenter обладает всеми
        необходимыми правами и полномочиями на управление и содержание
        CosmetologyCenter.by.</p>
        <div class="off-data">
            <div class="upoln">
              <p><em>Подпись уполномоченного лица</em></p>
              <p itemprop="name"><strong>Киселёв А.В.</strong></p>
              <p>Владелеца <strong>ООО "Косметологический центр"</strong></p>
            </div>
            <div class="facsimilie">
              <img src="https://power.org.ua/images/izgotovlenie-faksimile.png"
                class="podpis">
              <img src="https://abali.ru/wp-content/uploads/2011/04/pechat.png"
                class="pechat">
            </div>
          </div>
          <p class="podtverzdenie">Для подтверждения действительности этого сертификата, пожалуйста,
            посетите
            наш веб-сайт CosmetologyCenter.by или свяжитесь с нами по телефону <a
              href="tel:+375295656566">+375 (29) 565-65-66</a>.</p>
</figure>


{%endblock%}

CosmetologyCenter/main/templates/main/create_review.html
{% extends 'layout.html' %}

{% load static %}

{% block head %}
<link rel="stylesheet" href="{% static 'css/main/create_review.css'%}"/>
{% endblock %}

{% block main %}
<form method="POST" enctype="multipart/form-data">
    {%csrf_token%}
    {%for f in form%}
    <p><label for="{{f.id_for_label}}">{{f.label}}: </label>{{f}}</p>
    <div>{{f.errors}}</div>
    {%endfor%}
    <input type="submit" value="Оставить отзыв" >
</form>
{% endblock %}

CosmetologyCenter/main/templates/main/home.html
{% extends 'layout.html' %}

{% load static %}

{% block head %}
<link rel="stylesheet" href="{% static 'css/main/home.css'%}"/>

<title>Главная страница</title>
{% endblock %}


{% block main %}
<h1>Главная страница</h1>

<h2>Последняя актуальная новость:</h2>

<div class="news">
    <h2>{{news.title}}</h2>
    <h3>{{news.essence}}</h3>
    <img src="{{news.photo.url}}" width="500em" height="300em">
    <a href="{% url 'main:news' %}">Показать больше</a>
</div>

<h2>Многиее выбирают:</h2>

<ul class="service-list">
    {% for service in services %}
    <div class="service-details">
        <li>
            <img src="{{ service.image.url }}">
            <h3>{{ service.service_name }}</h3>
            <a href="{% url 'services:service-detail' service.id %}">Подробнее</a>
        </li>
    </div>
    {% endfor %}
</ul>

<h2>Партнеры:</h2>

<ul class="partners-list">
    <li class="partner-block">

        <figure>
            <p><img src="../media/images/DocDoc.png" alt="DocDoc" width="70em" height="70em"></p>
            <figcaption> <a href="https://docdoc.ru/clinic/spec/kosmetologiya"
                    target="_blank">DocDoc</a></figcaption>
        </figure>

    </li>
    <li class="partner-block">
        <figure>
            <p><img src="../media/images/SM-Estetica.png" alt="SM-Estetica" width="80em" height="80em"></p>
            <figcaption> <a href="https://www.sm-estetica.ru/"
                    target="_blank">SM-Estetica</a></figcaption>
        </figure>

    </li>   
</ul>

<div class="sidebar-banners">
    {% for banner in banners %}
        <a href="{{ banner.target_url }}">
            <img src="{{ banner.image.url }}" alt="{{ banner }}" width="300em" height="200em" />
        </a>
    {% endfor %}
</div>

<div class="banner" id="banner1">
    <a href="https://goldapple.ru/" target="_blank"><img width="50%" height="250px" src="../media/images/GoldenApple.png" alt="Баннер Золотое яблоко"></a>
</div>
<div class="banner" id="banner2">
    <a href="https://www.google.com/url?sa=i&url=https%3A%2F%2Fmila.by%2Freklamnaya-igra%2F&psig=AOvVaw2IeK1ntBulxg4htfk5gWDd&ust=1695718104606000&source=images&cd=vfe&opi=89978449&ved=0CBMQ3YkBahcKEwioot2_sMWBAxU" target="_blank"><img width="50%" height="250px" src="../media/images/Mila.jpg" alt="Баннер Милы"></a>
</div>
<form id="rotationForm" {% if not user.is_superuser %}style="display: none;"{% endif %}>
    <label for="rotationInterval">Интервал ротации (сек):</label>
    <input  type="number" id="rotationInterval" value="2">
    <button type="button" id="startRotation">Start Rotation</button>
    <button type="button" id="stopRotation">Stop Rotation</button>
</form>

<div class="scroll">
    <img id="right_woman" src="../media/images/womanRight.png" alt="Woman on the right">
    <img id="left_woman" src="../media/images/womanLeft.png" alt="Woman on the left">
    <img id="bottom_woman" src="../media/images/womanBottom.png" alt="Woman on the bottom">
    <img id="center_woman" src="../media/images/womanCenter.png" alt="Woman in the center">
</div>
  
<script src="{% static 'js/banner.js'%}"></script>
<script src="{% static 'js/animation_scroll.js'%}"></script>
{% endblock %}

CosmetologyCenter/main/templates/main/job.html
{% extends 'layout.html' %}

{% load static %}

{% block head %}
<link rel="stylesheet" href="{% static 'css/main/job.css'%}"/>

<title>Vacancies Page</title>
{% endblock %}

{% block main %}
<div class="vacancies-content">
    <h1>Актуальные вакансии</h1>
    {% for v in vacancies %}
    <h3>{{ v.type_of_job }}</h3>
    <h4>{{ v.description }}</h4>
    <div class="clear"></div> 
    {% endfor %}
</div>
{%endblock%}

CosmetologyCenter/main/templates/main/js_sandbox.html
{% extends "layout.html" %}

{% load static %}

{% block head %}
<link rel="stylesheet" href="{% static 'css/main/js_sandbox.css'%}"/>

<title>Sandbox</title>
{% endblock %} 

{% block main %}

<style>
    body {
        background-image: none;
    }
</style>

<div>
    <h2>Theme Customization</h2>
    <form>
        <label for="fontSize">Font Size: </label>
        <input type="number" id="fontSize" min="10" max="50" value="16" onchange="changeFontSize()">
        <br>
        <br>
        <label for="textColor">Text Color: </label>
        <input type="color" id="textColor" value="#000000" onchange="changeTextColor()">
        <br>
        <br>
        <label for="bgColor">Background Color: </label>
        <input type="color" id="bgColor" value="#ffffff" onchange="changeBackgroundColor()">
    </form>
</div>

<br>
<br>

<button id="colorButton">Change theme</button>
<br>
<br>

<button onclick="transposeTable()">Transpose table</button>
<br>
<br>
<button onclick="addRow()">Add row</button>
<button onclick="addColumn()">Add column</button>
<br>
<br>
<label for="maxCells">Max cells to select in a row/column:</label>
<input type="number" id="maxCells" min="1" value="1">
<br>
<br>
<label for="tableSize">Table size:</label>
<input type="number" id="tableSize" min="1" value="5">
<button onclick="createNewTable()">Create table</button>
<br>
<br>
<table id="myTable"></table>

<div>
    <h2>Functional Inheritance (Prototype-based)</h2>
    <div>
        <h3>Service Info</h3>
        <p>Name: <span id="serviceName"></span></p>
        <p>Price: <span id="servicePrice"></span></p>
        <p>Time: <span id="serviceTime"></span></p>
        <p>Service Info: <span id="serviceInfo"></span></p>
    </div>
    <div>
        <h3>Message Info</h3>
        <p>Name: <span id="messageName"></span></p>
        <p>Price: <span id="messagePrice"></span></p>
        <p>Time: <span id="messageTime"></span></p>
        <p>Type: <span id="messageType"></span></p>
        <p>Service Info: <span id="messageInfo"></span></p>
    </div>
</div>

<hr>

<div>
    <h2>Class and Extends</h2>
    <div>
        <h3>Service Info (Class)</h3>
        <p>Name: <span id="serviceNameClass"></span></p>
        <p>Price: <span id="servicePriceClass"></span></p>
        <p>Time: <span id="serviceTimeClass"></span></p>
        <p>Service Info: <span id="serviceInfoClass"></span></p>
    </div>
    <div>
        <h3>Message Info (Class)</h3>
        <p>Name: <span id="messageNameClass"></span></p>
        <p>Price: <span id="messagePriceClass"></span></p>
        <p>Time: <span id="messageTimeClass"></span></p>
        <p>Type: <span id="messageTypeClass"></span></p>
        <p>Service Info: <span id="messageInfoClass"></span></p>
    </div>
</div>

<br>
<br>

<form id="form">
    <label for="data">Введите информацию о владельцах дачных участков:</label><br>
    <textarea id="data" rows="5" cols="40"></textarea><br>
    <button type="button" onclick="findOwners()">Найти владельцев</button><br><br>

    <div id="result"></div>
</form>

<br>
<br>

<script src="{% static 'js/table.js'%}"></script>
<script src="{% static 'js/oop.js'%}"></script>
<script src="{% static 'js/individual_task.js'%}"></script>
<script src="{% static 'js/themes.js'%}"></script>
{%endblock%}

CosmetologyCenter/main/templates/main/news.html
{% extends 'layout.html' %}

{% load static %}

{% block head %}
<link rel="stylesheet" href="{% static 'css/main/news.css'%}"/>

<title>Новости</title>
{% endblock %}

{% block main %}
<section>
  {% for new in news%}
  <article>
    <h2>{{new.title}}</h2>
    <h4 class="short-description">{{new.essence}}</h4>
    <img src="{{new.photo.url}}">
    <details>
      <summary>
       больше
      </summary>
      {{new.description}}
    </details>
  </article>
  {%endfor%}
</section>
<div style="margin-bottom: 30px;"></div>
{% endblock %}

CosmetologyCenter/main/templates/main/price-list.html
{% extends "layout.html" %}

{% block head %}
<title>Прайс-лист</title>
{% endblock %}

{% block main %}
<div>
  <h1>Прайс-лист</h1>
  {% for service_type, services in services_by_type.items %}
    <details>
      <summary>{{ service_type.designation }}</summary>
      <ul>
        {% for service in services %}
          <li><a href="{% url 'services:service-detail' service.id %}">{{ service.service_name }}</a>  ${{ service.price }}</li>
        {% endfor %}
      </ul>
    </details>
  {% endfor %}
</div>
{% endblock %}

CosmetologyCenter/main/templates/main/promotional_code.html
{% extends "layout.html" %}

{% load static %}

{% block head %}
<link rel="stylesheet" href="{% static 'css/main/promotional_code.css'%}"/>

<title>FAQ Page</title>
{% endblock %}

{% block main %}

<div class="promo-container">
    <h1>Действующие промокоды:</h1>
    {% for p in actual_promotional_code %}
        <h3>{{ p.value }} - {{ p.discount }}%</h3>
    {% endfor %}
    <a href="../media/images/promo.txt" download>Скачать список актуальных промокодов</a>
</div>

<div class="promo-container">
    <h1>Промокоды в архиве:</h1>
    {% for p in archive_promotional_code %}
        <h3>{{ p.value }} - {{ p.discount }}%</h3>
    {% endfor %}
</div>

{%endblock%}

CosmetologyCenter/main/templates/main/reviews.html
{% extends "layout.html" %}

{% load static %}

{% block head %}
<link rel="stylesheet" href="{% static 'css/main/reviews.css'%}"/>

<title>Отзывы</title>
{% endblock %}

{% block main %}
<div class="main-content">
    <a class="leave-review-button" href="{% url 'main:create_rewiew' %}">Оставить свой отзыв</a>
    <div class="review-list">
        <h1>Отзывы</h1>
        {% for r in reviews %}
        <div class="review">
            <h2 class="review-author">{{ r.author }}</h2>
            <h3 class="review-text">{{ r.text }}</h3>
            <div class="review-meta">
                <h4 class="review-rating">Оценка: {{ r.rating }}</h4>
                <h4 class="review-date">Добавлен: {{ r.date_added }}</h4>
            </div>
        </div>
        <hr class="review-divider">
        {% endfor %}
    </div>
</div>
{%endblock%}