CosmetologyCenter/CosmetologyCenter/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),

    path('', include('main.urls')),
    path('cart/', include('cart.urls')),
    path('doctors/', include('doctors.urls')),
    path('services/', include('services.urls')),
    path('appointments/', include('appointments.urls')),
    path('stats/', include('stats.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

CosmetologyCenter/appointments/urls.py
from django.urls import path
from . import views

app_name = 'appointments'

urlpatterns = [
    path('', views.appointment_list_for_user, name='appointment_list_for_user'),
    path('create_appointment_item/', views.create_appointment_item, name='create_appointment_item'),
    path('create_appointments/', views.create_appointments, name='create_appointments'),
]

CosmetologyCenter/cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_details, name='cart_details'),
    path('add_to_cart/<int:service_id>/', views.add_to_cart, name='add_to_cart'),
    path('remove_in_cart/<int:appointment_item_id>/', views.cart_remove, name='cart_remove'),
]

CosmetologyCenter/appointments/models.py
from django.db import models
from django.contrib.auth.models import User
from services.models import Service
from main.models import Client


# Create your models here.
class Appointment(models.Model):
    client = models.ForeignKey(Client, on_delete=models.CASCADE)
    appointmentItem = models.ForeignKey('AppointmentItem', on_delete=models.CASCADE)


class AppointmentItem(models.Model):
    service = models.ForeignKey(Service, on_delete=models.CASCADE)
    date = models.DateField(default=None)
    time = models.TimeField(default=None)

    class Meta:
        ordering = ["date", "time"]

    def __str__(self):
        return f"{self.date} {self.time}"

CosmetologyCenter/appointments/forms.py
from django import forms
from .models import AppointmentItem
from services.models import Service
from main.models import Client


class AppointmentItemForm(forms.ModelForm):
    class Meta:
        model = AppointmentItem
        fields = ['service', 'date', 'time']

    date = forms.DateField(widget=forms.DateInput(attrs={'type': 'date'}))
    time = forms.TimeField(widget=forms.TimeInput(attrs={'type': 'time'}))

    def __init__(self, user, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['service'].queryset = Service.objects.filter(doctor__user=user)


class ClientForm(forms.ModelForm):
    class Meta:
        model = Client
        fields = ['first_name', 'last_name', 'date_of_birth', 'email', 'town', 'phone_number']

CosmetologyCenter/appointments/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from .forms import AppointmentItemForm, ClientForm
from .models import Appointment
from cart.models import Cart


# Create your views here.
@login_required
def appointment_list_for_user(request):
    user = request.user
    appointments = Appointment.objects.filter(appointmentItem__service__doctor__user=user)
    return render(request, 'appointments/appointment-list.html', {'appointments': appointments})


@login_required
def create_appointment_item(request):
    if request.method == 'POST':
        form = AppointmentItemForm(request.user, request.POST)
        if form.is_valid():
            appointment_item = form.save()
            return redirect('appointments:appointment_list_for_user')
    else:
        form = AppointmentItemForm(request.user)

    return render(request, 'appointments/create-appointment-item.html', {'form': form})


def create_appointments(request):
    if request.method != 'POST':
        form = ClientForm()
        return render(request, 'appointments/create-client.html', {'form': form})

    form = ClientForm(request.POST)
    if not form.is_valid():
        return render(request, 'appointments/create-client.html', {'form': form})

    client = form.save()
    cart = Cart(request)

    for item in cart:
        appointment = Appointment.objects.create(client = client, appointmentItem = item)

    cart.clear()

    return redirect('main:home')

CosmetologyCenter/appointments/templates/appointments/appointment-list.html
{% extends "layout.html" %}

{% block head %}
<title>Записи</title>
{% endblock %}

{% block main %}
<h1>Список записей:</h1>

<table width="100%">
    <thead>
        <tr>
            <th>Имя</th>
            <th>Фамилия</th>
            <th>Дата и Время</th>
            <th>Кабинет</th>
            <th>Услуга</th>
        </tr>
    </thead>
    <tbody>
        {% for appointment in appointments %}
        <tr>
            <td>{{ appointment.client.first_name }}</td>
            <td>{{ appointment.client.last_name }}</td>
            <td>{{ appointment.appointmentItem }}</td>
            <td>{{ appointment.appointmentItem.service.office }}</td>
            <td>{{ appointment.appointmentItem.service.service_name }}</td>
        </tr>
        {% endfor %}
    </tbody>    
</table>

<form method="get" action="{% url 'appointments:create_appointment_item' %}">
    <button type="submit">Добавить время для записи</button>
</form>
{% endblock %}

CosmetologyCenter/appointments/templates/appointments/create-appointment-item.html
{% extends "layout.html" %}

{% block head %}
<title>Создать время для записи</title>
{% endblock %}

{% block main %}
<h1>Создать запись на услугу</h1>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Создать</button>
</form>
{% endblock %}

CosmetologyCenter/appointments/templates/appointments/create-client.html
{% extends "layout.html" %}

{% block head %}
<title>Оформление записи</title>
{% endblock %}

{% block main %}
<h1>Заполните информацию о себе</h1>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Записаться</button>
</form>
{% endblock %}