CosmetologyCenter/CosmetologyCenter/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),

    path('', include('main.urls')),
    path('cart/', include('cart.urls')),
    path('doctors/', include('doctors.urls')),
    path('services/', include('services.urls')),
    path('appointments/', include('appointments.urls')),
    path('stats/', include('stats.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

CosmetologyCenter/cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_details, name='cart_details'),
    path('add_to_cart/<int:service_id>/', views.add_to_cart, name='add_to_cart'),
    path('remove_in_cart/<int:appointment_item_id>/', views.cart_remove, name='cart_remove'),
]

CosmetologyCenter/doctors/urls.py
from django.urls import path, include
from . import views

app_name = 'doctors'

urlpatterns = [ 
    path('', include('django.contrib.auth.urls')),
    path('doctors/', views.index, name='doctors-list'),
    path('doctor/<int:pk>/', views.DoctorDetailView.as_view(), name='doctor-detail'),
]

CosmetologyCenter/main/urls.py
from django.urls import path
from . import views


app_name = 'main'

urlpatterns = [ 
    path('', views.home, name='home'),
    path('about/', views.about, name='about'),
    path('prices/', views.price_list, name='price-list'),
    path('news/', views.news, name = 'news'),
    path('FAQ/', views.faq, name = 'FAQ'),
    path('sandbox/', views.sandbox, name = 'sandbox'),
    path('create_rewiew/', views.create_review, name = 'create_rewiew'),
    path('rewiews/', views.reviews, name = 'rewiews'),
    path('privacy_policy/', views.privacy_policy, name = 'privacy_policy'),
    path("promotional_code/", views.promotional_code, name='promotional_code'),
    path('vacancies/', views.vacancies, name = 'vacancies'),
    path('js_sandbox/', views.js_sandbox, name = 'js_sandbox')
]

CosmetologyCenter/services/urls.py
from django.urls import path
from . import views

app_name = 'services'

urlpatterns = [ 
    path('', views.index, name='services-list'),
    path('service/<int:pk>/', views.ServiceDetailView.as_view(), name='service-detail'),
]

CosmetologyCenter/stats/urls.py
from . import views
from django.urls import path

app_name = 'stats'

urlpatterns = [
    path('report/', views.report, name='report'),
]

CosmetologyCenter/templates/layout.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta name="author" content="Kiselev Andrey">
        <meta name="description"
            content="Косметологический центр предоставляет широкий круг услуг">
        <meta name="keywords"
            content="красота, здоровье, центр">

        {% block head %}{% endblock %}

        <link rel="icon" href="../media/images/lotus.png" type="image/x-icon">
        <link rel="stylesheet" href="{% static 'css/layout/layout.css'%}"/>
    </head>

    <body>
        <div class="progress"></div>
        <aside>
            <ul>
                <li><a href="{% url 'main:home' %}">Главная</a></li>
                <li><a href="{% url 'doctors:doctors-list' %}">Сотрудники</a></li>
                <li><a href="{% url 'services:services-list' %}">Услуги</a></li>
                <li><a href="{% url 'main:price-list' %}">Прайс-лист</a></li>
                <li><a href="{% url 'main:about' %}">О компании</a></li>
                <li><a href="{% url 'main:rewiews' %}">Отзывы</a></li>
                <li><a href="{% url 'cart:cart_details' %}">Корзина</a></li>
                <li><a href="{% url 'main:promotional_code' %}">Промокоды</a></li>
                <li><a href="{% url 'main:vacancies' %}">Вакансии</a></li>
                <li><a id="sandbox" href="{% url 'main:sandbox' %}">Дополнительно</a></li>
                <li><a href="{% url 'main:js_sandbox' %}">Дополнительно JS</a></li>
                <li><a href="{% url 'stats:report' %}" onclick="return checkAge(event)">Статистика</a></li>
                {% if user.is_authenticated %}
                <li><a href="{% url 'appointments:appointment_list_for_user' %}">Записи</a></li>
                <li><a href="{% url 'doctors:logout' %}">Выйти</a></li>
                {% else %}
                <li><a href="{% url 'doctors:login'%}?next={{request.path}}">Войти</a></li>
                {% endif %}

                <div id ="countdown"></div>
            </ul>
        </aside>

        <main>
            {% block main %} {% endblock %}
        </main>

        <footer>
            <div>
                <p>&copy; 2023 Косметологический центер <span>CosmetologyCenter</span></p>
                <nav>
                    <ul>
                        <li><a href="{%url 'main:FAQ'%}">Словарь терминов и понятий</a></li>
                        <li><a href="{% url 'main:privacy_policy'%}">Политика конфиденциальности</a></li>
                    </ul>
                </nav>
            </div>
        </footer>

         <script src="{% static 'js/progress_bar.js'%}"></script>
         <script src="{% static 'js/timer.js'%}"></script>
         <script src="{% static 'js/age.js'%}"></script>
    </body>
</html>