CosmetologyCenter/CosmetologyCenter/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),

    path('', include('main.urls')),
    path('cart/', include('cart.urls')),
    path('doctors/', include('doctors.urls')),
    path('services/', include('services.urls')),
    path('appointments/', include('appointments.urls')),
    path('stats/', include('stats.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

CosmetologyCenter/appointments/urls.py
from django.urls import path
from . import views

app_name = 'appointments'

urlpatterns = [
    path('', views.appointment_list_for_user, name='appointment_list_for_user'),
    path('create_appointment_item/', views.create_appointment_item, name='create_appointment_item'),
    path('create_appointments/', views.create_appointments, name='create_appointments'),
]

CosmetologyCenter/cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_details, name='cart_details'),
    path('add_to_cart/<int:service_id>/', views.add_to_cart, name='add_to_cart'),
    path('remove_in_cart/<int:appointment_item_id>/', views.cart_remove, name='cart_remove'),
]

CosmetologyCenter/cart/models.py
from django.conf import settings
from appointments.models import AppointmentItem


class Cart(object):
    def __init__(self, request):
        self.session = request.session
        cart = self.session.get(settings.CART_SESSION_ID)

        if not cart:
            cart = self.session[settings.CART_SESSION_ID] = []

        self.cart = cart    


    def add(self, appointment_item):
        appointment_item_id = str(appointment_item.id)

        if appointment_item_id not in self.cart:
            self.cart.append(appointment_item_id)

        self.save()


    def save(self):
        self.session[settings.CART_SESSION_ID] = self.cart

        self.session.modified = True


    def remove(self, appointment_item):
        appointment_item_id = str(appointment_item.id)
        if appointment_item_id in self.cart:
            self.cart.remove(appointment_item_id)

        self.save()


    def __iter__(self):
        appointment_items = AppointmentItem.objects.filter(id__in=self.cart)

        for item in appointment_items:
            yield item


    def __len__(self):
        return len(self.cart)


    def clear(self):
        self.session[settings.CART_SESSION_ID] = []
        self.session.modified = True


    def get_total_price(self):
        appointment_items = AppointmentItem.objects.filter(id__in=self.cart)

        return sum(item.service.price for item in appointment_items)

CosmetologyCenter/cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from cart.models import Cart
from services.models import Service
from cart.form import AppointmentItemForm
from appointments.models import AppointmentItem
from django.core.exceptions import PermissionDenied
from appointments.models import AppointmentItem


def add_to_cart(request, service_id):
    if request.method == 'POST':
        service = get_object_or_404(Service, id=service_id)
        form = AppointmentItemForm(request.POST, service = service)

        if form.is_valid():
            cart = Cart(request)
            cart.add(form.cleaned_data['appointment_item'])
        else:
            print(form.errors)
    return redirect('services:services-list')


def cart_details(request):
    cart = Cart(request)
    return render(request, 'cart/cart-detail.html', {'cart': cart})
  

def cart_remove(request, appointment_item_id):
  if not request.user.is_authenticated:
      raise PermissionDenied("No acsess")

  cart = Cart(request)
  appointment_item = get_object_or_404(AppointmentItem, id=appointment_item_id)
  cart.remove(appointment_item)
  return redirect('cart:cart_details')

CosmetologyCenter/cart/templates/cart/cart-detail.html
{% extends 'layout.html' %}

{% load static %}

{% block head %}
<link rel="stylesheet" href="{% static 'css/cart/cart-detail.css'%}"/>

<title>Корзина</title>
{% endblock %}

{% block main %}
<h1>Ваша корзина</h1>

<table class="cart" width="100%">
    <thead>
        <tr>
            <th>Услуга</th>
            <th>Дата</th>
            <th>Время</th>
            <th>Цена</th>
            <th>Удаление</th>
        </tr>
    </thead>
    <tbody>
        {% for item in cart %}
        <tr>
            <td>{{ item.service.service_name }}</td>
            <td>{{ item.date }}</td>
            <td>{{ item.time }}</td>
            <td class="num">${{ item.service.price }}</td>
            <td><a href="{% url 'cart:cart_remove' item.id %}">Удалить</a></td>
        </tr>
        {% endfor %}
        <tr class="total">
            <td>Total</td>
            <td colspan="5"></td>
            <td class="num total_price">
                ${{ cart.get_total_price|floatformat:"2" }}
            </td>
        </tr>
    </tbody>    
</table>

<hr>
<form method="post" action="{% url 'appointments:create_appointments' %}" id="appointmentForm">
    {% csrf_token %}
    <button type="button" id="ageConfirmationButton">Записаться</button>
</form>

<input type="number" id="dob">
<button onclick="applyPromo()">Применить скидку</button>
<script src="{% static 'js/promo.js'%}"></script>

<script>
    document.getElementById("ageConfirmationButton").addEventListener("click", function () {
        var result = confirm("Подтвердите, что вам 18 лет или старше.");
        if (result === true) {
            document.getElementById("appointmentForm").submit();
        }
    });
</script>
{% endblock %}